version: 2.1

setup: true

orbs:
  path-filtering: circleci/path-filtering@1.0.0

workflows:
  Setup:
    jobs:
      - path-filtering/filter:
          base-revision: master
          config-path: ./BackEnd/config.yml
          mapping: |
            BackEnd/.* run-backend-jobs true
